const ActionType = {
  LOGIN: `LOGIN`,
  LOGOUT: `LOGOUT`,
  FILL_USERS_LIST: `FILL_USERS_LIST`,
  LOGIN_ERROR: `LOGIN_ERROR`,
  TODO_ERROR: `TODO_ERROR`,
  SERVER_ERROR: `SERVER_ERROR`,
  FILL_TODO_LIST: `FILL_TODO_LIST`,
  USERS_LIST_ERROR: `USERS_LIST_ERROR`,
  NOTHING: `NOTHING`
};

export default ActionType;
